-- DDL for rc_rawlocations table in Redshift
CREATE TABLE IF NOT EXISTS public.rc_rawlocations (
    StoreID INT NOT NULL,
    LocationName VARCHAR(255) NOT NULL,
    LocationOwnerType INT,
    ABN VARCHAR(20),
    State VARCHAR(50),
    StoreType INT,
    StoreTypeName VARCHAR(100),
    DateOpened DATE,
    DateClosed DATE,
    ShortCode VARCHAR(20),
    TradeDays INT,
    Territory VARCHAR(50),
    Country VARCHAR(50),
    Postcode VARCHAR(10),
    Address1 VARCHAR(255),
    Address2 VARCHAR(255),
    Suburb VARCHAR(100),
    Phone VARCHAR(20),
    Latitude FLOAT8,
    Longitude FLOAT8,
    AvgOrderTime INT,
    Bitmask INT,
    PaymentGatewayCustomerID VARCHAR(100),
    OpeningTimesSunday TIME,
    OpeningTimesMonday TIME,
    OpeningTimesTuesday TIME,
    OpeningTimesWednesday TIME,
    OpeningTimesThursday TIME,
    OpeningTimesFriday TIME,
    OpeningTimesSaturday TIME,
    OpeningTimesPublicHoliday TIME,
    ClosingTimesSunday TIME,
    ClosingTimesMonday TIME,
    ClosingTimesTuesday TIME,
    ClosingTimesWednesday TIME,
    ClosingTimesThursday TIME,
    ClosingTimesFriday TIME,
    ClosingTimesSaturday TIME,
    ClosingTimesPublicHoliday TIME,

    PRIMARY KEY (StoreID)
);

