-- This model performs an upsert (merge) from the raw rc_rawMembers data into the cdmcustomer table
-- Uses dbt_utils.surrogate_key for id 

{{ config(materialized='incremental', unique_key='MemberID') }}

with source as (
    select
        MemberCount,
        MemberNo,
        MemberID,
        Surname,
        GivenNames,
        UserName,
        ActiveStatus,
        Registered,
        Verified,
        Referred,
        Email,
        CardType,
        FavouriteStoreName,
        FavouriteStoreID,
        IssuingStoreName,
        IssuingStoreID,
        DateOfBirth,
        RegistrationDateTime,
        RegistrationDate,
        RegistrationTime,
        VerificationDateTime,
        VerificationDate,
        ExpiryDateTime,
        ExpiryDate,
        LastUpdateDate,
        LastUpdateDateTime,
        CreationDate,
        Sex,
        SendEmail,
        SendSMS,
        Phone,
        Mobile,
        State,
        PostCode,
        Address1,
        Address2,
        Suburb,
        Country,
        DeviceID,
        DeviceType,
        PackageName,
        GroupName,
        GroupID,
        PointsAwarded,
        PointsRedeemed,
        MoneyAwarded,
        MoneyRedeemed,
        PointsBalance,
        MoneyBalance,
        LastTxnDate,
        FirstTxnDate,
        LastTxnDateTime,
        FirstTxnDateTime,
        LastAdminTxnDate,
        FirstAdminTxnDate,
        LastAdminTxnDateTime,
        FirstAdminTxnDateTime,
        VerificationType,
        source_name,
        source_row_count
    from {{ ref('rc_rawmembers') }}
    where ActiveStatus = 1 and Verified = 1
)

select
    {{ dbt_utils.generate_surrogate_key(['MemberID']) }} as CustomerID,
    MemberCount,
    MemberNo,
    MemberID,
    Surname,
    GivenNames,
    UserName,
    ActiveStatus,
    Registered,
    Verified,
    Referred,
    Email,
    CardType,
    FavouriteStoreName,
    FavouriteStoreID,
    IssuingStoreName,
    IssuingStoreID,
    DateOfBirth,
    RegistrationDateTime,
    RegistrationDate,
    RegistrationTime,
    VerificationDateTime,
    VerificationDate,
    ExpiryDateTime,
    ExpiryDate,
    LastUpdateDate,
    LastUpdateDateTime,
    CreationDate,
    Sex,
    SendEmail,
    SendSMS,
    Phone,
    Mobile,
    State,
    PostCode,
    Address1,
    Address2,
    Suburb,
    Country,
    DeviceID,
    DeviceType,
    PackageName,
    GroupName,
    GroupID,
    PointsAwarded,
    PointsRedeemed,
    MoneyAwarded,
    MoneyRedeemed,
    PointsBalance,
    MoneyBalance,
    LastTxnDate,
    FirstTxnDate,
    LastTxnDateTime,
    FirstTxnDateTime,
    LastAdminTxnDate,
    FirstAdminTxnDate,
    LastAdminTxnDateTime,
    FirstAdminTxnDateTime,
    VerificationType,
    source_name,
    source_row_count
from source

{% if is_incremental() %}
    where MemberID not in (select MemberID from {{ this }})
{% endif %}
